### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by haknick** [Rouslan/nativecompile#1]
Hey Rouslan,

Have there been any new updates to this ?

**Comment by Rouslan** [comment]
The latest work is in the symtable branch, where the machine code was generated from the abstract syntax tree instead of byte-code, and the machine code generating classes kept track of which registers were being used. Although currently it doesn't even run.

It's been a while since I touched this. I have been working on a couple of other things that I haven't uploaded to GitHub. I intended to finish this eventually, but if there is actually some interest to this, besides my own, I would be happy to continue working on it now.

**Comment by Rouslan** [comment]
So there is no misunderstanding: I'm going to take the lack of follow up reply as a lack of interest. I'll make one or two more updates and go back to the unrelated projects.
